### ISSUE TITLE
Support for variable opening hours

### ISSUE THREAD

**Issue by chadgh** [arteria/django-openinghours#17]
Is it currently possible to support a locations opening hours that are different at different times of the year?

For example, a public library might have different hours during the summer months when kids aren't in school from the hours that they have during the school year.

These aren't closed times, but they are different regular hours times for different dates.

**Comment by philippeowagner** [comment]
It is possible to define closing hours, e.g. for holiday. What about to define two sets of hours, for example _library-regular_ and _library-holiday_. If _library-holiday_ applies use closing hours on  _library-regular_ vice-versa.

**Comment by chadgh** [comment]
Ya. I think I could make that work. So you are suggesting having two (or however many I need) Companies, that are really just regular hours for different times of the year?

**Comment by philippeowagner** [comment]
Not perfect, but _yes_ – to bypass a more complex a costly solution for your use case.

**Comment by chadgh** [comment]
OK. I'll work with that. Thanks.
