### ISSUE TITLE
Setting Opening Hours

### ISSUE THREAD

**Issue by ttbohemian** [arteria/django-openinghours#21]
Hello guys,

I'm new to Django and new to Python, but : 

I have installed successfully the app,in the admin it's work,
 but i cannot add the opening class object to a field as ForeinKey : 

I think I'm missing something... I also set in settings.py 
OPENINGHOURS_PREMISES_MODEL = 'app.Example'

Is there any solution, to attach the opening hours to a custom model? 
I already know is my fault, but can I have some tips? 
Thank you

```
from openinghours.models import OpeningHours


class Example(model.Models):
    opening_hours = models.ForeignKey('OpeningHours',on_delete=models.PROTECT)

```

**Comment by ttbohemian** [comment]
` opening_hours = models.ForeignKey('**openinghours.OpeningHours**',on_delete=models.PROTECT,blank=True, null=True,related_name='open_hours')
`

I think is the answer...

**Comment by walterrenner** [comment]
@ttbohemian please close this issue if you managed to solve your problem
