### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by oesah** [arteria/django-openinghours#23]
Currently there are no validations in place to check for the following: 

1. `from_hour` can be bigger then `to_hour` (in one set)
2. `from_hour` in set 2 can be smaller then `to_hour` in set 1.

Is there a way to implement that? 

This app is very nice and also very unique. There aren't any useful other modules. So it would be nice, if we can upgrade this module for professional use. I can also assist you other than reporting bugs and feature requests. Let me know what I can do!

**Comment by philippeowagner** [comment]
_.., if we can upgrade this module for professional use._  😂  

Just RTFM, since [0.0.2](https://github.com/arteria/django-openinghours/blob/147e8d169324d8e196936b4eea11e27b17b8683e/CHANGELOG.txt#L28) it is possible to define [opening hours passing midnight](https://github.com/arteria/django-openinghours/blob/147e8d169324d8e196936b4eea11e27b17b8683e/openinghours/utils.py#L102-L107).

**Comment by oesah** [comment]
To be more clear, this is the scenario that should NOT work:

Monday - set 1 - 08:00 - 14:00
Monday - set 2 - 09:00 - 16:00

Note that the set 2 starting time is smaller than the set 1 ending time. Is that what you mean with your proposal?

**Comment by philippeowagner** [comment]
```
              now
OH1  0800      |      1200   1400       1700        
    ---=================-------===========------------
OH2       0900 |   1100      
    --------=========---------------------------------
               |
             Yes, we're open! 
```

I do not agree. There are use cases for that.

**Comment by oesah** [comment]
OH1 has two sets right? So the first DB entry would be 0800 - 1200 and the second entry would be 1400 - 1700, correct? Because then it isn't what I mean. 

Here is a screenshot: 
<img width="855" alt="bildschirmfoto 2017-03-27 um 14 21 59" src="https://cloud.githubusercontent.com/assets/4014723/24356092/d1a379ea-12f8-11e7-8cb1-64f5319db7c9.png">
