### ISSUE TITLE
Opening hours are not ordered by weekday, when no Data is given for a day

### ISSUE THREAD

**Issue by walterrenner** [arteria/django-openinghours#8]
The [companyOpeningHoursList templatetag](https://github.com/arteria/django-openinghours/blob/master/openinghours/templatetags/openinghours_tags.py#L78) just "appends" the days where no openinghours are defined.

So when a company is closed on monday and saturday is will render the days tuesday to friday and sunday and append monday and saturday after saturday, which is confusing for the customers.

Example:
```
Tuesday: 9 - 5
Wednesday: 9 - 5
Thursday: 9 - 5
Friday: 9 - 5
Sunday: 9 - 5
Monday: closed
Sunday: closed
```

I expected the following output:
```
Monday: closed
Tuesday: 9 - 5
Wednesday: 9 - 5
Thursday: 9 - 5
Friday: 9 - 5
Sunday: 9 - 5
Sunday: closed
```

**Comment by fmalina** [comment]
Fixed [here](https://github.com/arteria/django-openinghours/commit/aab347b583becc459e0a5934137e341ac31107d2).

Feel free to comment on other fixes and features in [my fork](https://github.com/arteria/django-openinghours/compare/master...fmalina:master), but please open a separate ticket so I can get it ready for a PR and merge.

**Comment by walterrenner** [comment]
@fmalina would you mind open a PR for this issue.
